function hmm() {
console.log('hmm');
console.log('hmm');  
console.log
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
console.log('hmm');
}
hmm();
